name: Azure ML Trigger Pipeline

on:
  # 月曜日の 11:27 (JST) に処理を実行する。
  # UTC の 02:27 は JST だと 11:27 。
  # schedule:
  #   - cron: "27 2 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: aml_yamls

permissions:
  id-token: write
  contents: read

jobs:
  create-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{secrets.AZURE_CREDENTIALS}}"
      - name: Install ML extension for az command
        run: az extension add --name ml --version 2.11.0
      - name: Create And Register ML Model
        run: az ml job create --file training_pipeline_job.yml -g ${{secrets.AZURE_RESOURCE_GROUP_NAME}} -w ${{secrets.AZURE_ML_WORKSPACE_NAME}}
